In [1]:
import numpy as np

### tạo 1 mảng numpy từ danh sách của python

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [6]:
np.array([3.14, 6,5, 7, 8]) ### ép các kiểu dữ liệu khác về float

array([3.14, 6.  , 5.  , 7.  , 8.  ])

In [7]:
np.array([1, 2, 3, 4], dtype = "float64")

array([1., 2., 3., 4.])

In [8]:
a1 = np.array([1, 2, 3, 4])
print(a1)

[1 2 3 4]


In [10]:
print(type(a1))

<class 'numpy.ndarray'>


In [12]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [13]:
a2.shape

(2, 3)

In [14]:
a2[:, 0]

array([1, 4])

In [15]:
print(a2[:, 0])

[1 4]


In [16]:
a2.size

6

### tạo một cái mảng numpy từ các hàm có sẵn

In [18]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.zeros((4, 5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [42]:
np.zeros(2) ### tạo 1 mảng chỉ toàn số 0

array([0., 0.])

In [41]:
np.ones((2, 6), dtype = int) ### tạo một mảng mà chỉ toàn số 1

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [40]:
np.arange(0, 100, 4) ### tạo một mảng có điểm đầu và điểm cuối có bước nhảy 

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [39]:
np.full((2, 9), 67) ### tạo một mảng cùng một giá trị nhập vào 

array([[67, 67, 67, 67, 67, 67, 67, 67, 67],
       [67, 67, 67, 67, 67, 67, 67, 67, 67]])

In [38]:
np.linspace(0, 3, 7, dtype = int) ### in ra các giá trị từ đầu đến cuối theo số giá trị đã cho 

array([0, 0, 1, 1, 2, 2, 3])

### RANDOM

In [45]:
np.random.random((5, 5)) # random các số từ 0 đến 1

array([[0.1567029 , 0.75062496, 0.07267919, 0.33627878, 0.30789289],
       [0.55559559, 0.64990968, 0.18546895, 0.71239124, 0.07759724],
       [0.22090517, 0.02051581, 0.97811438, 0.15664665, 0.90611719],
       [0.33771252, 0.24780433, 0.39205907, 0.93206859, 0.30305961],
       [0.90683528, 0.70617101, 0.88482586, 0.81413183, 0.15379827]])

In [48]:
np.random.normal(0, 1, (3, 3))

array([[ 0.52457534, -1.26008776,  2.07041365],
       [-1.16882853, -0.58643804,  0.48107469],
       [-0.69511698,  0.09217967,  0.54536756]])

In [54]:
a3 = np.random.randint(4, 9, size = 6)
print(a3)

[8 4 4 7 4 4]


In [56]:
a3 = np.random.randint(4, 9, (3, 4))
print(a3)

[[6 7 8 6]
 [4 6 4 6]
 [8 7 8 6]]


<hr style="height:5px;border:none;background:linear-gradient(to right, #1E90FF, #00FF7F);">

### ARRAY INDEXING AND SLICING

### one- dimensional subarray

In [62]:
x1 = np.random.randint(4, 10, 8)
print(x1)

[6 9 4 9 9 5 7 6]


In [66]:
print(x1[-1], x1[5], x1[0])

6 5 6


### multi- dimensional subarray

In [68]:
x2 = np.random.randint(1, 10, (3, 4))
x2

array([[8, 8, 8, 9],
       [2, 9, 4, 1],
       [2, 8, 7, 7]], dtype=int32)

In [72]:
print(x2[2, 3])

7


In [73]:
x2[2, 3] = 10

In [74]:
x2

array([[ 8,  8,  8,  9],
       [ 2,  9,  4,  1],
       [ 2,  8,  7, 10]], dtype=int32)

### Slicing
### x[start:end:step]

In [75]:
x1

array([6, 9, 4, 9, 9, 5, 7, 6], dtype=int32)

In [76]:
x1[3:8]

array([9, 9, 5, 7, 6], dtype=int32)

In [77]:
x1[::4]

array([6, 9], dtype=int32)

In [78]:
x2

array([[ 8,  8,  8,  9],
       [ 2,  9,  4,  1],
       [ 2,  8,  7, 10]], dtype=int32)

In [79]:
x2[:2, :3]

array([[8, 8, 8],
       [2, 9, 4]], dtype=int32)

In [80]:
x2[1:2, 0:2]

array([[2, 9]], dtype=int32)

In [81]:
x2[:2]

array([[8, 8, 8, 9],
       [2, 9, 4, 1]], dtype=int32)

In [82]:
x2[:, :3]

array([[8, 8, 8],
       [2, 9, 4],
       [2, 8, 7]], dtype=int32)

### Reshape và Transpose

In [84]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])